### ISSUE TITLE
RSS contains encoded HTML

### ISSUE THREAD

**Issue by janboddez** [victoriadrake/victoriadrake.github.io#6] opened 2021-07-30 11:04 UTC
Since a week or so, `content:encoded` tags inside the RSS feed contain actually encoded HTML rather than plain HTML, e.g., inside `CDATA` tags, causing readers to display the HTML itself.

Screenshot (this is Feedly): 
![afbeelding](https://user-images.githubusercontent.com/8428432/127644035-dc23eace-270b-4622-af2c-8650ce6a725e.png)

**Comment by victoriadrake** [comment] 2021-08-10 11:00
Thanks for letting me know, Jan! This is fixed now with https://github.com/victoriadrake/victoriadrake.github.io/commit/cbcd15b29f6d4bcce9e52a3451300ee4ee3c74bf and my latest on Feedly seems to look as intended.

It doesn't appear that Feedly updates articles it's previously pulled in, so the one in your screenshot still has HTML in it. 😢

**Closed as completed by victoriadrake** 2021-08-10 11:00 UTC
